path = '/media/cleveland/TECKLA CPIR/20160601_141124_FAC450_TA_SusceptibilityMouse5_1_1/18';
NPro =51472;
NPoints=101;
NTE=4;
% Interleaves=13;
% NPropi=NPro/Interleaves;

%trajectory, along one spoke

fid = fopen(fullfile(path,'traj'));
coords = fread(fid,[3,inf],'double');
fclose(fid);
coords = reshape(coords,[3 NPoints NTE NPro]);
r = squeeze(sqrt(coords(1,:,:,:).^2 + coords(2,:,:,:).^2 + coords(3,:,:,:).^2));
traj_bruk=reshape(squeeze(coords(:,:,1,:)),[3 NPoints*NPro]);%generated by Bruker Scanner;

% coords= coords(:,:,1:NPro-Interleaves);
% coords=reshape(coords,[3 NPoints NPropi Interleaves]);
% fclose(fid);



% maxr=max(r(:));
% coords=coords/maxr/2;
% plot(r(133,1:51470),'--rs','LineWidth',2,'MarkerEdgeColor','k','MarkerFaceColor','g','MarkerSize',5);

fid = fopen(fullfile(path,'traj_measured'));
coords1 = fread(fid,[3,inf],'double');
coords1 = reshape(coords1,[3 NPoints NPro]);
fclose(fid);
r1 = squeeze(sqrt(coords1(1,:,:).^2 + coords1(2,:,:).^2 + coords1(3,:,:).^2));
maxr=max(r1(:));
coords1=coords1/maxr/2;
traj_syn=reshape(coords1,[3 NPoints*NPro]);%synthesized

% coords1 = coords1(:,:,1:NPro-Interleaves);
% coords1=reshape(coords1,[3 NPoints NPropi-1 Interleaves]);






n=10;%the nth interleave;

for i=10:15
%     
%     LL=NPropi*(n-1)*NPoints+1+(i-1)*100*NPoints;
%     UL=NPropi*(n-1)*NPoints+i*100*NPoints;
    LL=(i-1)*NPoints*50+1;
    UL=i*NPoints*50;
    

scatter3(traj_bruk(1,LL:UL),traj_bruk(2,LL:UL),traj_bruk(3,LL:UL),20,'b','o');
hold on;
scatter3(traj_syn(1,LL:UL),traj_syn(2,LL:UL),traj_syn(3,LL:UL),30,'r','s');
hold off;

end